"""initial email extractor schema

Revision ID: 78f509b95848
Revises:
Create Date: 2026-04-19 13:16:28.912852

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78f509b95848"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extraction_run",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pipeline_name", sa.String(length=120), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("person_name", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=False),
        sa.Column("processed_items", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_extraction_run_domain"), "extraction_run", ["domain"], unique=False)
    op.create_index(op.f("ix_extraction_run_pipeline_name"), "extraction_run", ["pipeline_name"], unique=False)
    op.create_index(op.f("ix_extraction_run_status"), "extraction_run", ["status"], unique=False)
    op.create_table(
        "discovered_email",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["extraction_run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "email", name="uq_discovered_email_run_email"),
    )
    op.create_index(op.f("ix_discovered_email_email"), "discovered_email", ["email"], unique=False)
    op.create_index(op.f("ix_discovered_email_run_id"), "discovered_email", ["run_id"], unique=False)
    op.create_index(op.f("ix_discovered_email_source"), "discovered_email", ["source"], unique=False)
    op.create_table(
        "email_verification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("discovered_email_id", sa.Integer(), nullable=False),
        sa.Column("syntax_valid", sa.Boolean(), nullable=True),
        sa.Column("mx_record_present", sa.Boolean(), nullable=True),
        sa.Column("smtp_status", sa.String(length=32), nullable=False),
        sa.Column("smtp_message", sa.Text(), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["discovered_email_id"], ["discovered_email.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_verification_discovered_email_id"), "email_verification", ["discovered_email_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_verification_discovered_email_id"), table_name="email_verification")
    op.drop_table("email_verification")
    op.drop_index(op.f("ix_discovered_email_source"), table_name="discovered_email")
    op.drop_index(op.f("ix_discovered_email_run_id"), table_name="discovered_email")
    op.drop_index(op.f("ix_discovered_email_email"), table_name="discovered_email")
    op.drop_table("discovered_email")
    op.drop_index(op.f("ix_extraction_run_status"), table_name="extraction_run")
    op.drop_index(op.f("ix_extraction_run_pipeline_name"), table_name="extraction_run")
    op.drop_index(op.f("ix_extraction_run_domain"), table_name="extraction_run")
    op.drop_table("extraction_run")
    # ### end Alembic commands ###
